### ISSUE TITLE
Flutter代码模板报错

### ISSUE THREAD

**Issue by 47sang** [AweiLoveAndroid/Flutter-learning#10]
[https://github.com/AweiLoveAndroid/Flutter-learning/blob/master/code_plugins/dart.json](https://github.com/AweiLoveAndroid/Flutter-learning/blob/master/code_plugins/dart.json)
第102行到109行前面的空格使用tab自动空格会出类型错误，改成空格的就没事了。
问题code：
			"	@override",
			"	Path getClip(Size size) {",
			"		//TODO:",
			"	}",
			"",
			"	@override",
			"	bool shouldReclip(CustomClipper<Path> oldClipper) => false;",
			"	}",

**Comment by AweiLoveAndroid** [comment]
已更新
